// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

/*
Package kademlia is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	ProtocolPackage
*/
package kademlia

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtocolPackage_MessageSent int32

const (
	ProtocolPackage_PING      ProtocolPackage_MessageSent = 0
	ProtocolPackage_PONG      ProtocolPackage_MessageSent = 1
	ProtocolPackage_STORE     ProtocolPackage_MessageSent = 2
	ProtocolPackage_FINDNODE  ProtocolPackage_MessageSent = 3
	ProtocolPackage_FINDVALUE ProtocolPackage_MessageSent = 4
)

var ProtocolPackage_MessageSent_name = map[int32]string{
	0: "PING",
	1: "PONG",
	2: "STORE",
	3: "FINDNODE",
	4: "FINDVALUE",
}
var ProtocolPackage_MessageSent_value = map[string]int32{
	"PING":      0,
	"PONG":      1,
	"STORE":     2,
	"FINDNODE":  3,
	"FINDVALUE": 4,
}

func (x ProtocolPackage_MessageSent) Enum() *ProtocolPackage_MessageSent {
	p := new(ProtocolPackage_MessageSent)
	*p = x
	return p
}
func (x ProtocolPackage_MessageSent) String() string {
	return proto.EnumName(ProtocolPackage_MessageSent_name, int32(x))
}
func (x *ProtocolPackage_MessageSent) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtocolPackage_MessageSent_value, data, "ProtocolPackage_MessageSent")
	if err != nil {
		return err
	}
	*x = ProtocolPackage_MessageSent(value)
	return nil
}
func (ProtocolPackage_MessageSent) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type ProtocolPackage struct {
	ClientID    []byte                       `protobuf:"bytes,1,req,name=clientID" json:"clientID,omitempty"`
	Ip          *string                      `protobuf:"bytes,2,req,name=ip" json:"ip,omitempty"`
	ListenPort  *int32                       `protobuf:"varint,3,req,name=listenPort" json:"listenPort,omitempty"`
	MessageSent *ProtocolPackage_MessageSent `protobuf:"varint,4,req,name=messageSent,enum=kademlia.ProtocolPackage_MessageSent" json:"messageSent,omitempty"`
	FindID      []byte                       `protobuf:"bytes,5,opt,name=findID" json:"findID,omitempty"`
	FindValue   []byte                       `protobuf:"bytes,6,opt,name=findValue" json:"findValue,omitempty"`
	//
	// message ContactInfo{
	// optional bytes contactID = 1;
	// optional string address = 2;
	// optional bytes distance = 3;
	// }
	ContactsKNearest [][]byte `protobuf:"bytes,7,rep,name=contactsKNearest" json:"contactsKNearest,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ProtocolPackage) Reset()                    { *m = ProtocolPackage{} }
func (m *ProtocolPackage) String() string            { return proto.CompactTextString(m) }
func (*ProtocolPackage) ProtoMessage()               {}
func (*ProtocolPackage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtocolPackage) GetClientID() []byte {
	if m != nil {
		return m.ClientID
	}
	return nil
}

func (m *ProtocolPackage) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *ProtocolPackage) GetListenPort() int32 {
	if m != nil && m.ListenPort != nil {
		return *m.ListenPort
	}
	return 0
}

func (m *ProtocolPackage) GetMessageSent() ProtocolPackage_MessageSent {
	if m != nil && m.MessageSent != nil {
		return *m.MessageSent
	}
	return ProtocolPackage_PING
}

func (m *ProtocolPackage) GetFindID() []byte {
	if m != nil {
		return m.FindID
	}
	return nil
}

func (m *ProtocolPackage) GetFindValue() []byte {
	if m != nil {
		return m.FindValue
	}
	return nil
}

func (m *ProtocolPackage) GetContactsKNearest() [][]byte {
	if m != nil {
		return m.ContactsKNearest
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtocolPackage)(nil), "kademlia.ProtocolPackage")
	proto.RegisterEnum("kademlia.ProtocolPackage_MessageSent", ProtocolPackage_MessageSent_name, ProtocolPackage_MessageSent_value)
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8d, 0x41, 0x4f, 0xb3, 0x40,
	0x10, 0x40, 0x3f, 0x16, 0xe8, 0x07, 0x53, 0xc4, 0x75, 0x4e, 0x7b, 0xdc, 0x34, 0x31, 0xd9, 0x13,
	0x07, 0x8f, 0xde, 0x4c, 0xc0, 0x86, 0xa8, 0x40, 0xac, 0xf6, 0xbe, 0xa1, 0x63, 0x43, 0x4a, 0x77,
	0x1b, 0x76, 0xfd, 0x0d, 0xfe, 0x6d, 0x53, 0xa2, 0xd1, 0x78, 0x7b, 0x6f, 0x66, 0x32, 0x0f, 0xf2,
	0xd3, 0x64, 0xbd, 0xed, 0xed, 0x58, 0xcc, 0x80, 0xc9, 0x41, 0xef, 0xe8, 0x38, 0x0e, 0x7a, 0xf5,
	0xc1, 0xe0, 0xb2, 0xfb, 0x5a, 0x76, 0xba, 0x3f, 0xe8, 0x3d, 0x21, 0x87, 0xa4, 0x1f, 0x07, 0x32,
	0xbe, 0x2e, 0x45, 0x20, 0x99, 0xca, 0x10, 0x80, 0x0d, 0x27, 0xc1, 0x24, 0x53, 0x29, 0x22, 0xc0,
	0x38, 0x38, 0x4f, 0xa6, 0xb3, 0x93, 0x17, 0xa1, 0x64, 0x2a, 0xc6, 0x5b, 0x58, 0x1e, 0xc9, 0x39,
	0xbd, 0xa7, 0x0d, 0x19, 0x2f, 0x22, 0xc9, 0x54, 0x7e, 0x73, 0x5d, 0x7c, 0x57, 0x8a, 0x3f, 0x85,
	0xe2, 0xe9, 0xe7, 0x18, 0x73, 0x58, 0xbc, 0x0d, 0x66, 0x57, 0x97, 0x22, 0x96, 0x81, 0xca, 0xf0,
	0x0a, 0xd2, 0xb3, 0x6f, 0xf5, 0xf8, 0x4e, 0x62, 0x31, 0x8f, 0x04, 0xf0, 0xde, 0x1a, 0xaf, 0x7b,
	0xef, 0x1e, 0x1a, 0xd2, 0x13, 0x39, 0x2f, 0xfe, 0xcb, 0x50, 0x65, 0xab, 0x1a, 0x96, 0xbf, 0x7f,
	0x25, 0x10, 0x75, 0x75, 0xb3, 0xe6, 0xff, 0x66, 0x6a, 0x9b, 0x35, 0x0f, 0x30, 0x85, 0x78, 0xf3,
	0xd2, 0x3e, 0x57, 0x9c, 0x61, 0x06, 0xc9, 0x7d, 0xdd, 0x94, 0x4d, 0x5b, 0x56, 0x3c, 0xc4, 0x0b,
	0x48, 0xcf, 0xb6, 0xbd, 0x7b, 0x7c, 0xad, 0x78, 0xf4, 0x19, 0x00, 0x00, 0xff, 0xff, 0x2c, 0xf1,
	0x35, 0xb9, 0x24, 0x01, 0x00, 0x00,
}
